### ISSUE TITLE
key frame selection and mkvframecount "system cannot find file specified"

### ISSUE THREAD

**Issue by Buwaka** [Zeght/Macron#1]
You use the keyframe as index instead of just simply using it as start and end keyframe

```
    l = keyframes[bisect.bisect_right(keyframes, range[0])-1]
    r = keyframes[bisect.bisect_left(keyframes, range[1])]
```

I think it should be something like this:

```
    start = range.split(" ")[0]
    end = range.split(" ")[1]
    l = bisect.bisect_right(keyframes, start)-1
    r = bisect.bisect_left(keyframes, end)
```

and mkvframecount just throws the error "system cannot find file specified", which doesn't make much sense to me because the filepath is alright (even within the function).

that's what I could find thus far.

**Comment by Zeght** [comment]
Keyframes part: You probably misunderstand what bisect does.
MKV part: Macro uses command line interface of mkvmerge,  to make it work you need to make mkvmerge callable from cmd as "mkvmerge". You can do that by adding mkvmerge folder to PATH environment variable or by copying mkvmerge.exe to the folder that already in PATH.
